In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = np.array([i for i in range(10)])

In [9]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [11]:
b = np.array(c)

In [12]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(b)

numpy.ndarray

In [14]:
b = np.array(a, dtype = float)

In [15]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]

In [16]:
b = np.array(a, dtype = int)

In [17]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = np.array(a, dtype = float)

In [19]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [20]:
b = np.array(a, dtype = str)

In [21]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [22]:
a = ['abc', 1, 2, 3]

In [23]:
b = np.array(a)

In [24]:
b

array(['abc', '1', '2', '3'], dtype='<U11')

In [26]:
b.dtype

dtype('<U11')

In [27]:
a = [0, 1, 2, 3.125]

In [28]:
b = np.array(a)

In [29]:
b

array([0.   , 1.   , 2.   , 3.125])

In [30]:
b.dtype

dtype('float64')

In [31]:
b[0]

0.0

In [32]:
b[1]

1.0

In [33]:
b[3]

3.125

In [34]:
b.ndim

1

In [35]:
b.shape

(4,)

2D array

In [36]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
             [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
             [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [37]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
b.shape

(3, 10)

In [39]:
b.size

30

In [40]:
b[0][0]

0

In [41]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [43]:
b[:2, :3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [44]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [45]:
c = b[1:, 5:]

In [46]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [47]:
c[1, 4] = 999

In [48]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [49]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [50]:
b[1, 5] = 555

In [51]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [52]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [53]:
c = b[1:, 5:].copy()

In [54]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [55]:
c[0, 0] = 777

In [56]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [57]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [58]:
b[1, 5] = 888

In [59]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 888,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [60]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

### Data types

In [61]:
b = np.array([1., 2., 3.], dtype = np.float32)

In [62]:
b

array([1., 2., 3.], dtype=float32)

In [63]:
b = np.array([1., 2., 3.], dtype = np.float64)

In [64]:
b

array([1., 2., 3.])

In [65]:
b.dtype

dtype('float64')

In [66]:
b = np.array([1, 2, 3], dtype = np.int32)

In [67]:
b

array([1, 2, 3])

In [69]:
b.dtype

dtype('int32')

In [70]:
b = np.array([1, 2, 3], dtype = np.int64)

In [71]:
b

array([1, 2, 3], dtype=int64)

In [72]:
b.dtype

dtype('int64')