## Операции с векторами

Загрузим библиотеку NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])

In [3]:
b = np.array([5, 6, 7, 8, 9])

In [4]:
a.size

5

In [5]:
b.size

5

In [6]:
a.shape

(5,)

In [7]:
b.shape

(5,)

### Сложение векторов

In [8]:
c = a + b

In [9]:
c

array([ 5,  7,  9, 11, 13])

In [10]:
c.size

5

In [11]:
c.shape

(5,)

Сравним, что делает оператор "+" со списками в  Python

In [12]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [13]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Еще один способ

In [14]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

### Вычитание векторов

In [15]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [16]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

Альтернативный способ:

In [17]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

При вычитании векторов их размерность должна совпадать:

In [18]:
a.shape == b.shape

True

### Умножение вектора на скаляр

In [19]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [20]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [21]:
c = -10 * a

In [22]:
c

array([-50, -40, -80, -40, -30])

In [23]:
c = 0.5 * a
c

array([2.5, 2. , 4. , 2. , 1.5])

Сравним с умножением натурального числа на список

(результат не тот - увеличение длины списка, а не умножение вектора на скаляр):

In [24]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

Альтернативные способы умножения массива на скаляр:

In [25]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [26]:
# Вариант 1
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [27]:
# Вариант 2
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [28]:
# Вариант 3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

#### Скалярное произведение векторов

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [30]:
a.shape

(3,)

In [31]:
b.shape

(3,)

In [32]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [33]:
a @ b

32

In [34]:
sp = np.dot(a, b)
sp

32

#### Операции над матрицами

In [41]:
A = np.array([[0, 1], 
              [2, 3],
              [4, 5]])

In [42]:
B = np.array([[6, 7], 
              [8, 9],
              [10, 11]])

In [44]:
A.shape

(3, 2)

In [45]:
B.shape

(3, 2)

#### Сложение матриц

In [47]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Альтернативный способ

In [49]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Вычитание матриц

In [51]:
A = np.array([[ 6,  8],
           [10, 12],
           [14, 16]])

In [52]:
B = np.array([[ 16,  48],
           [1, 2],
           [4, 6]])

In [53]:
D = A - B
D

array([[-10, -40],
       [  9,  10],
       [ 10,  10]])

In [54]:
D = np.subtract(A, B)
D

array([[-10, -40],
       [  9,  10],
       [ 10,  10]])

#### Умножение матрицы на скаляр

In [55]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [56]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [58]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])