In [1]:
import numpy as np

#### Умножение матриц

In [2]:
X1 = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [3]:
X2 = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

Число столбцов первой матрицы должно быть равно числу строк второй матрицы:

In [4]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [5]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [6]:
Z.shape

(3, 4)

Как получен элемент матрицы Z нулевой строки и нулевого столбца:

In [7]:
Z[0, 0]

29

In [8]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

Как получен элемент матрицы Z нулевой строки и нулевого столбца:

In [9]:
Z[0, 1]

32

In [10]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2[1, 1]

32

#### Модуль numpy.linalg: возведение матрицы в квадрат

In [11]:
A = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [12]:
A_square = np.dot(A, A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [14]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### Создание единичной матрицы

Единичная матрица - квадратная матрица с единицами по главной диагонали и нулями в остальных ячейках

In [15]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Умножение матрицы на единичную матрицу

In [16]:
A = np.array([[1, 2],
             [2, 3],
             [3, 4]])

Случай 1

In [17]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [18]:
np.dot(A, I)

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

Случай 2

In [19]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.dot(I, A)

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

Транспонирование матрицы

In [21]:
A = np.array([[11, 13],
             [16, 9],
             [8, 15]])

In [22]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

Альтернативный способ

In [23]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

Рассмотрим матрицы X и Y:

In [25]:
X = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [26]:
Y = np.array([[0, 1],
             [3, 4],
             [6, 7],
             [2, 5]])

In [27]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [28]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

Вычисление определителя и ранга матрицы

Пример 1

In [29]:
A = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [30]:
np.linalg.det(A)

0.0

In [31]:
np.linalg.matrix_rank(A)

2

Пример 2

In [32]:
B = np.array([[7, 4, 5],
             [8, 3, 2],
             [6, 10, 12]])

In [33]:
np.linalg.det(B)

85.99999999999997

In [34]:
np.linalg.matrix_rank(B)

3

Пример 3 (можно узнать только ранг матрицы, но не определитель, так как она не квадратная)

In [35]:
С = np.array([[7, 4],
             [8, 3],
             [6, 10]])

In [36]:
np.linalg.matrix_rank(B)

3

### Вычисление обратной матрицы

In [37]:
B = np.array([[7, 4, 5],
             [8, 3, 2],
             [6, 10, 12]])

In [38]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [39]:
B_inv2 = np.linalg.inv(B_inv)

In [40]:
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])