In [1]:
import numpy as np

### Автоматическое создание массивов

In [2]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

По умолчанию ряд чисел начинается с 0, но можно явно задать начало последовательности:

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Последовательность с шагом 2

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

В обратном порядке

In [7]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

В обратном порядке с шагом 2

In [8]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

Дробный шаг

In [9]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

numpy.linspase - то же самое, но нужно учитывать, что правая граница будет включена. 
вместо шага указываем нужное количество элементов (100):


In [10]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

numpy.logspace - обе границы включены, но это не сами числа, а степени числа 10:

In [11]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

Генерирование случайных чисел

numpy.random.sample - случайные числа с равномерным распределением в промежутке [0.0, 1.0)
                                                                                 
                                                                                 
Случайное число

In [12]:
np.random.sample()

0.20595397850892372

Одномерный массив из 3-х чисел

In [13]:
np.random.sample(3)

array([0.11019535, 0.40407839, 0.20554709])

Двумерный массив 2х3

In [14]:
np.random.sample((2, 3))

array([[0.87341829, 0.92576919, 0.80535947],
       [0.68638223, 0.19455651, 0.67206375]])

Массив 48х64х3

(например, это может быть случайное изображение с высотой 48, шириной 64 и значениями яркости трех цветов для каждого пикселя)

In [15]:
np.random.sample((48, 64, 3))

array([[[0.3299782 , 0.35151802, 0.54724952],
        [0.59492424, 0.2569284 , 0.72054509],
        [0.94785141, 0.11094772, 0.06219527],
        ...,
        [0.93626943, 0.28355347, 0.37966377],
        [0.85547922, 0.22043796, 0.2973802 ],
        [0.1596027 , 0.90130261, 0.50451248]],

       [[0.87520824, 0.65806906, 0.92041587],
        [0.88788604, 0.9487206 , 0.33579132],
        [0.47347112, 0.81093395, 0.39232339],
        ...,
        [0.83387177, 0.23813816, 0.53504039],
        [0.18016692, 0.11518773, 0.92883769],
        [0.45955308, 0.78938193, 0.27857217]],

       [[0.73731197, 0.42463542, 0.79691652],
        [0.53899921, 0.54252574, 0.21678398],
        [0.19827747, 0.07940949, 0.84073341],
        ...,
        [0.90748445, 0.41517259, 0.52492647],
        [0.21060942, 0.21013719, 0.97483957],
        [0.0582251 , 0.49866297, 0.1633589 ]],

       ...,

       [[0.44106631, 0.7336233 , 0.49617762],
        [0.57691725, 0.50151708, 0.7335697 ],
        [0.61712771, 0

numpy.random.randn - случайные числа с нормальным распределением
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [16]:
np.random.randn(10)

array([ 0.75372664, -0.07842437, -0.22783787, -0.30513248, -1.34612611,
        0.0160347 ,  0.16640012,  0.87220543, -1.89574897,  1.72238548])

In [17]:
np.random.randn(3, 4)

array([[-1.03589564,  1.34410223, -1.48136176,  0.29013939],
       [-0.09417364,  0.67917407,  0.26626939,  0.31030577],
       [ 0.25213212,  0.42986113,  1.15043551,  0.2453045 ]])

numpy.random.randint - массив целых чисел

Например, одномерный массив из 10 случайных целых чисел в промежутке [0, 100)

In [18]:
np.random.randint(0, 100, 10)

array([27, 35, 28, 23, 39, 11, 78, 31, 57, 30])

Двумерный массив 3х4 из случайных целых чисел в промежутке [0, 10)

In [19]:
np.random.randint(0, 10, (3, 4))

array([[6, 8, 1, 2],
       [1, 7, 0, 5],
       [7, 9, 6, 0]])

**numpy.random.choice** Случайный выбор элементов массива

In [20]:
b = np.array([1, 4, 6, 12, 55, 6, 23, 67])

In [21]:
np.random.choice(b)

1

In [22]:
np.random.choice(b, 3)

array([23, 23, 67])

**numpy.random.seed** - инициализация генератора случайных чисел.

Может использоваться для последующей воспроизводимости (будут генерироваться те же числа, если установить одинаковый seed)

In [23]:
np.random.seed(42)

In [26]:
np.random.randint(0, 10, 3)

array([2, 6, 7])

Изменение формы массива

In [27]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
# Можно указать требуемое число строк, а вместо числа столбцов поставить -1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
# Указать только число столбцов
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
# inplace
a.resize(3, 4)

In [35]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Соединение Массивов

для наглядности возьмем два массива с нулями и единицами

In [38]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

Соединение строк (вертикально)

In [40]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [42]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

Соединение столбцов (горизонтально)

In [43]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [44]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [45]:
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

Соединение в глубину (третье измерение)

In [46]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])