In [1]:
import numpy as np

Выбор данных

In [2]:
a = np.random.randint(0, 20, 10)
a

array([ 3, 15,  8, 10, 16,  2, 11, 10,  7, 17])

In [3]:
a[a > 10]

array([15, 16, 11, 17])

In [4]:
a[(a > 10) & (a % 2 == 0)]

array([16])

In [5]:
a[(a > 10) | (a % 3 == 0)]

array([ 3, 15, 16, 11, 17])

***numpy.where*** - первый вариант


In [6]:
a

array([ 3, 15,  8, 10, 16,  2, 11, 10,  7, 17])

In [7]:
# возвращает индексы чисел, удовлетворяющих условию
np.where(a > 10)

(array([1, 4, 6, 9], dtype=int64),)

In [8]:
a[np.where(a > 10)]

array([15, 16, 11, 17])

***numpy.where*** - второй вариант

In [9]:
a = [1, 4, 7]
b = [9, 2, 5]

In [10]:
#Если в условии True, то берем элемент из массива а,
# если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

Сортировка

In [11]:
a = np.array([[1, 3, 9, 9],
            [5, 0, 1, 5],
            [2, 7, 3, 5]])

In [12]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [13]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [14]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [15]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

Случайное перемешивание массивов

Одномерные массивы

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#inplace - на месте
np.random.shuffle(a)

In [18]:
a

array([7, 2, 1, 9, 8, 0, 5, 3, 4, 6])

Двумерные массивы

In [22]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
# inplace
np.random.shuffle(a)

In [24]:
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [ 3,  4,  5],
       [ 0,  1,  2]])

#### Математические действия с массивами

Применение математических функций

In [31]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [27]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [28]:
a.sum()

21

In [30]:
a.sum(axis = 1)

array([ 6, 15])

In [32]:
a.sum(axis = 0)

array([5, 7, 9])

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

In [35]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Broadcasting

In [38]:
a = np.array([[2, 5],
             [3, 4],
             [6, 1]])

In [39]:
b = np.array([1, 2])

In [40]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2 случай - совпадает только число строк

In [41]:
c = np.array([[1],
             [2],
            [3]])

In [42]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

Статистичесике функции

In [44]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 3,  9,  6,  4],
       [ 5, 11,  4,  9],
       [11,  7,  9,  4]])

In [45]:
a.min()

3

In [46]:
#min для каждого столбца
a.min(axis = 0)

array([3, 7, 4, 4])

In [47]:
#max по каждой строке
a.max(axis = 1)


array([ 9, 11, 11])

In [48]:
a.mean(axis = 0)

array([6.33333333, 9.        , 6.33333333, 5.66666667])

In [49]:
a.std(axis = 0)

array([3.39934634, 1.63299316, 2.05480467, 2.3570226 ])

Запись и чтение массива из файла

In [50]:
np.save('a.npy', a)

In [51]:
b = np.load('a.npy')


In [52]:
b

array([[ 3,  9,  6,  4],
       [ 5, 11,  4,  9],
       [11,  7,  9,  4]])